name: timeless
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  image_picker: ^1.1.2
  flutter:
    sdk: flutter


  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  get: ^4.7.2
  smooth_page_indicator: ^1.2.1
  flutter_switch: ^0.3.2
  salomon_bottom_bar: ^3.3.2

  # Firebase 
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_messaging: ^16.0.1

  # Auth
  # -> Passage en 6.x pour éviter l’erreur Pigeon et garder compatibilité avec firebase_auth 4.x
  google_sign_in: 6.2.1

  # Utilitaires
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  easy_localization: ^3.0.3
  url_launcher: ^6.2.6
  permission_handler: ^12.0.1
  country_picker: ^2.0.27
  advanced_search: ^2.2.6+1

  # Fichiers & Media
  file_picker: ^10.3.2
  path_provider: ^2.1.4  

  # Notifications
  flutter_local_notifications: ^19.4.0
  pinput: ^5.0.1
  
  # HTTP & Translation
  http: ^1.2.1
  
  # Video Player
  youtube_player_flutter: ^9.1.0

dependency_overrides:
  
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/
    - assets/icons/
    - assets/jobs.json
    - assets/cv/demo_cv.pdf
    - assets/translations/
